apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    isDefault: true
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600   # PostgreSQL 16
      timescaledb: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    editable: false
